#Cost feature is currently not implemented, do not enable.
costEnabled: false
ranks:
  0:
    name: Traveller
    time: 0
    cost: 0
  1:
    name: Sailor
    time: 43200
    cost: 500
  2:
    name: Settler
    time: 201600
    cost: 5000
  3:
    name: Chief
    time: 504000
    cost: 12500
  4:
    name: Mayor
    time: 720000
    cost: 50000
  5:
    name: Chancellor
    time: 1152000
    cost: 250000